name: vsa
description: VSA is a mobile application as a visualisation and monitoring tool for Vehicle Situational Awareness research project.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_value:
  built_collection:
  flutter_redux:
  redux:
  redux_epics:
  rxdart: ^0.23.1

  cupertino_icons: ^0.1.2
  cached_network_image: ^1.1.0

  shared_preferences: ^0.5.3+3
  mqtt_client: 5.6.0
  google_maps_flutter: ^0.5.19
  location: ^3.0.2
  flutter_compass: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^3.0.0
  build_runner:
  built_value_generator:
  
flutter:
  uses-material-design: true
  assets:
    # files
    - assets/files/intersections.csv
    - assets/files/simple_map_style.txt
      
    # images
    - assets/images/vehicles/car_other.png
    - assets/images/vehicles/car_self.png
    - assets/images/vehicles/cycle_other.png
    - assets/images/vehicles/cycle_self.png
    - assets/images/vehicles/motorbike_other.png
    - assets/images/vehicles/motorbike_self.png
    - assets/images/vehicles/pedestrian_other.png
    - assets/images/vehicles/pedestrian_self.png
    - assets/images/vehicles/scooter_other.png
    - assets/images/vehicles/scooter_self.png